name: Check file size
on:
  pull_request:
    branches: [main]

  # Allow manual workflow dispatch
  workflow_dispatch:

jobs:
  check-file-size:
    runs-on: ubuntu-latest
    steps:
      - name: Check large files
        uses: ActionsDesk/lfs-warning@v2.0
        with:
          filesizelimit: 10485760 # 10MB limit for HF Spaces sync
